## NEEDS UPDATED

experiment_name: "resnet_56_cifar10" # str
seed: 7112018

dataset: 
  !DCIFAR10
    download: true
    
batch_size: 128

gpus: [0]
validation_list: 'validation_cifar10_5%.txt' # list ints or name of list in 'lists' folder
fast_mode: true 

init_weights: true
model:
  !MResnetCIFAR
    num_blocks: [9,9,9]
    num_classes: 10

    # layers: [9, 9, 9] # these numbers multiplied by 2 and summed + 2 give N in ResNet-N, 
    #                   #  i.e. [9,9,9] = 1 + 2*9 + 2*9 + 2*9 + 1 = ResNet-56
    # num_output_classes: 10
    # zero_init_residual: false
    # groups: 1
    # width_scale_factor: 1
    # sparse_bn: false

epochs: 160
optimizer: 
  !OSGD 
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0001

scheduler: 
  !SMultiStep
    milestones: [80,120]
    gamma: 0.1

freeze_parameter_list: [] # list of regexes which if match a  fully qualified parameter name (i.e. resnet.model.bn_1.weight) have their weights frozen (not updated but calculated)  
  
transforms:
  - !PPRandomAffine {degrees: 0, translate: !!python/tuple [0.125, 0.125]} #should translate by 4 pixels since the images are 32x32
  - !PPRandomHorizontalFlip {}
  - !PPToTensor {}
  - &norm !PPElementwiseZeroing { input_shape: [3,32,32], mean_file: "./lists/cifar_10_pixel_mean.txt"}
transforms_test:
  - !PPToTensor {}
  - *norm # reference previous

target_transforms: []
target_transforms_test: []

trackers: # list of enums -> kwarg dict
  - !GradientsTracker {key: "gradients"}  # objects with 'yaml_tag' and inheriting from yaml.YAMLobject, can be instantiated this way!

    
